In [7]:
# 1. Multilayer Perceptron (MLP) for MNIST Dataset
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

x_train, x_test = x_train / 255.0, x_test / 255.0
x_train = x_train.reshape(-1, 28 * 28)
x_test = x_test.reshape(-1, 28 * 28)

model = keras.Sequential([
    layers.Dense(128, activation='relu', input_shape=(784,)),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5, validation_data=(x_test, y_test))

test_loss, test_acc = model.evaluate(x_test, y_test)
print(f"Test Accuracy: {test_acc*100:.4f}")

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.8787 - loss: 0.4200 - val_accuracy: 0.9640 - val_loss: 0.1171
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9704 - loss: 0.1000 - val_accuracy: 0.9698 - val_loss: 0.0971
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9792 - loss: 0.0693 - val_accuracy: 0.9718 - val_loss: 0.0930
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9835 - loss: 0.0530 - val_accuracy: 0.9761 - val_loss: 0.0776
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9882 - loss: 0.0372 - val_accuracy: 0.9779 - val_loss: 0.0735
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9738 - loss: 0.0875
Test Accuracy: 97.7900


In [6]:
# 2. Neural Network for Classifying News Articles (Reuters Dataset)
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

(x_train, y_train), (x_test, y_test) = keras.datasets.reuters.load_data(num_words=10000)

x_train = keras.preprocessing.sequence.pad_sequences(x_train, maxlen=300)
x_test = keras.preprocessing.sequence.pad_sequences(x_test, maxlen=300)

model = keras.Sequential([
    layers.Embedding(input_dim=10000, output_dim=128, input_length=300),
    layers.LSTM(64),
    layers.Dense(46, activation='softmax')  # 46 classes
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5, validation_data=(x_test, y_test))

test_loss, test_acc = model.evaluate(x_test, y_test)
print(f"Test Accuracy: {test_acc:.4f}")


2110848/2110848 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Epoch 1/5


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


281/281 ━━━━━━━━━━━━━━━━━━━━ 65s 222ms/step - accuracy: 0.4026 - loss: 2.5743 - val_accuracy: 0.5147 - val_loss: 1.8350
Epoch 2/5
281/281 ━━━━━━━━━━━━━━━━━━━━ 83s 225ms/step - accuracy: 0.5403 - loss: 1.8405 - val_accuracy: 0.5396 - val_loss: 1.8780
Epoch 3/5
281/281 ━━━━━━━━━━━━━━━━━━━━ 63s 226ms/step - accuracy: 0.5544 - loss: 1.7540 - val_accuracy: 0.5855 - val_loss: 1.7040
Epoch 4/5
281/281 ━━━━━━━━━━━━━━━━━━━━ 81s 221ms/step - accuracy: 0.6145 - loss: 1.5154 - val_accuracy: 0.6269 - val_loss: 1.5608
Epoch 5/5
281/281 ━━━━━━━━━━━━━━━━━━━━ 83s 223ms/step - accuracy: 0.6444 - loss: 1.3883 - val_accuracy: 0.6354 - val_loss: 1.4965
71/71 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.6483 - loss: 1.4543
Test Accuracy: 0.6354


In [11]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Example words
words = np.array(["apple", "banana", "cherry", "apple", "banana"]).reshape(-1, 1)

# One-hot encoding (use sparse_output instead of sparse)
encoder = OneHotEncoder(sparse_output=False)
encoded_words = encoder.fit_transform(words)

print("Original Words:\n", words.flatten())
print("One-Hot Encoded:\n", encoded_words)


Original Words:
 ['apple' 'banana' 'cherry' 'apple' 'banana']
One-Hot Encoded:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [13]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Load MNIST dataset
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Normalize and reshape data
x_train, x_test = x_train / 255.0, x_test / 255.0
x_train = x_train.reshape(-1, 28, 28, 1)
x_test = x_test.reshape(-1, 28, 28, 1)

# Define CNN model
model = keras.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

# Compile and train the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5, validation_data=(x_test, y_test))

# Evaluate model
test_loss, test_acc = model.evaluate(x_test, y_test)
print(f"Test Accuracy: {test_acc:.4f}")


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 57s 30ms/step - accuracy: 0.9052 - loss: 0.3147 - val_accuracy: 0.9853 - val_loss: 0.0455
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 57s 31ms/step - accuracy: 0.9857 - loss: 0.0471 - val_accuracy: 0.9878 - val_loss: 0.0411
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 57s 31ms/step - accuracy: 0.9907 - loss: 0.0295 - val_accuracy: 0.9916 - val_loss: 0.0292
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 79s 29ms/step - accuracy: 0.9921 - loss: 0.0233 - val_accuracy: 0.9904 - val_loss: 0.0294
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 83s 30ms/step - accuracy: 0.9946 - loss: 0.0173 - val_accuracy: 0.9903 - val_loss: 0.0367
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.9888 - loss: 0.0451
Test Accuracy: 0.9903


In [15]:
import numpy as np
from keras.preprocessing import image
from keras.applications.vgg16 import VGG16, preprocess_input, decode_predictions

# Load the VGG16 model pre-trained on ImageNet
model = VGG16(weights='imagenet')

# Load and preprocess the image
img_path = 'puppy.jpg'  # Ensure this image is in the same directory or provide the full path
img = image.load_img(img_path, target_size=(224, 224))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension
img_array = preprocess_input(img_array)  # Preprocess image for VGG16

# Make predictions
predictions = model.predict(img_array)
decoded_predictions = decode_predictions(predictions, top=3)[0]  # Get top 3 predicted labels

# Print predictions
print("Top predictions:")
for i, (imagenet_id, label, score) in enumerate(decoded_predictions):
    print(f"{i + 1}: {label} ({score:.2f})")


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 812ms/step
35363/35363 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Top predictions:
1: Pomeranian (0.75)
2: chow (0.25)
3: keeshond (0.00)
